# Generated by Django 4.2.3 on 2023-12-13 09:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("antiqueapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="login",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="customers",
                to="antiqueapp.login",
            ),
        ),
    ]
