# Generated by Django 4.2.3 on 2024-01-10 17:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("antiqueapp", "0002_alter_customer_login"),
    ]

    operations = [
        migrations.CreateModel(
            name="item",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(blank=True, null=True, upload_to="images")),
                ("name", models.CharField(max_length=30, null=True)),
                ("price", models.CharField(max_length=30, null=True)),
                ("description", models.CharField(max_length=30, null=True)),
                ("category", models.CharField(max_length=30, null=True)),
            ],
        ),
    ]
