# Generated by Django 4.2.3 on 2024-01-10 17:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("antiqueapp", "0003_item"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="description",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
