# Generated by Django 4.2.3 on 2024-01-14 18:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("antiqueapp", "0004_alter_item_description"),
    ]

    operations = [
        migrations.CreateModel(
            name="booking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=30, null=True)),
                ("adress", models.CharField(max_length=30, null=True)),
                ("image", models.ImageField(blank=True, null=True, upload_to="images")),
                ("name", models.CharField(max_length=30, null=True)),
                ("price", models.CharField(max_length=30, null=True)),
                ("description", models.CharField(max_length=100, null=True)),
                ("quantity", models.CharField(max_length=30, null=True)),
                ("booking_date", models.CharField(max_length=100)),
                (
                    "bookingstatus",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "itemid",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="antiqueapp.item",
                    ),
                ),
                (
                    "userid",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="antiqueapp.customer",
                    ),
                ),
            ],
        ),
    ]
