# Generated by Django 4.2.3 on 2024-01-14 19:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("antiqueapp", "0005_booking"),
    ]

    operations = [
        migrations.RenameField(
            model_name="booking",
            old_name="adress",
            new_name="phone",
        ),
    ]
